version: '3.7'

services:
  joke-db:
    env_file:
      - .env
    image: "postgres:13"
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-db}
    volumes:
      - './postgres:/var/lib/postgresql/data/'